class Worker{
    start()
    execute()
    stop()
    action()
}


class TaalcBot{}

class TaalcTransaction{
    transaction_batch
    from
    to    
    transaction_time
}

class CurrencyTransaction{
    currency
    amount
}

class NftTransaction{}
class MessageTransaction{}

class TransactionBatch{}

class TokensBag{
    user
    List[Token]
}

class TUser{

}

class TMember{
    telegram_id
}

class Wallet{
    member
    currency
    amount
}


class TaalcToken{
    name
}


class TMessage{    
    owner
    creator
    taalc_offer
    taalc_nft
    taalc_chat
    tg_id    
}

enum NftState{
    is_published
    on_bidding
    publishing
}

class TOffer{
    from_user
    to_user
    offer_type
    subject
    currency
    price
    state
    time
    duration
    message
    bidding_id
}

class MessageOffer{

}
enum OfferState{

}
enum OfferType{

}
class TChat{}


class Currency{}
class TaalcNft{
    
}

class TaalcNftToken{
    taalc_nft
}

class MessageNftToken{

}

class SystemService{
    install()
}
class WinService{}
class LinuxService{}

SystemService <|-- WinService
SystemService <|-- LinuxService

TMember <|-- TUser
TaalcToken <|-- Currency
TaalcToken <|-- TaalcNft
TMessage --> TChat
TMessage --> TaalcNft


Wallet -up-> Currency
Wallet -left-> TMember
CurrencyTransaction -up-|> TaalcTransaction
NftTransaction -up-|> TaalcTransaction
MessageTransaction --|> NftTransaction
CurrencyTransaction --> TransactionBatch
CurrencyTransaction --> Currency


TOffer --> OfferType
TOffer --> OfferState
TOffer --> TaalcNft
MessageOffer --|> TOffer

Wallet --|> TokensBag
TaalcNftToken --> TaalcNft
TaalcNftToken --> NftState
MessageNftToken --|> TaalcNftToken